<Project>

    <PropertyGroup>
        <Version>1.0.0-alpha.16</Version>
        <Authors>Kizari</Authors>
        <Company>Visium</Company>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <RepositoryUrl>https://github.com/Kizari/Anima.git</RepositoryUrl>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <Copyright>Copyright © 2024 Kizari</Copyright>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageReleaseNotes>https://github.com/Kizari/Anima/blob/main/CHANGELOG.md</PackageReleaseNotes>
        <RepositoryBranch>main</RepositoryBranch>
        <RepositoryCommit>231f2c38f98929de30627c90377892f5ebe7f1d0</RepositoryCommit>
        <PackageTags>source-generators;roslyn</PackageTags>
    </PropertyGroup>

</Project>