using System.Text;

namespace Anima.Utilities.SourceGeneration;

/// <summary>
/// A light wrapper around <see cref="System.Text.StringBuilder" /> that makes building source code strings easier.
/// </summary>
public sealed class SourceBuilder
{
    private readonly StringBuilder _builder = new();

    private int _indentation;
    private bool _shouldIndent;

    /// <summary>
    /// Instantiates a builder for a new source code string.
    /// </summary>
    public SourceBuilder()
    {
        // Automatically add boilerplate
        AppendLine("/// <auto-generated/>");
        AppendLine();
        AppendLine("#nullable enable");
        AppendLine();
    }

    /// <summary>
    /// Indents the caret by another 4 spaces.
    /// </summary>
    public SourceBuilder Indent()
    {
        _indentation++;
        return this;
    }

    /// <summary>
    /// Outdents the caret by another 4 spaces.
    /// </summary>
    public SourceBuilder Outdent()
    {
        _indentation = Math.Max(0, _indentation - 1);
        return this;
    }

    /// <summary>
    /// Appends a character to the source.
    /// </summary>
    public SourceBuilder Append(char value)
    {
        if (_shouldIndent)
        {
            _builder.Append(new string(' ', _indentation * 4));
        }

        _builder.Append(value);
        _shouldIndent = false;
        return this;
    }

    /// <summary>
    /// Appends a string to the source.
    /// </summary>
    public SourceBuilder Append(string value)
    {
        if (_shouldIndent)
        {
            _builder.Append(new string(' ', _indentation * 4));
        }

        _builder.Append(value);
        _shouldIndent = false;
        return this;
    }

    /// <summary>
    /// Appends a line break to the source.
    /// </summary>
    public SourceBuilder AppendLine()
    {
        _builder.AppendLine();

        _shouldIndent = true;
        return this;
    }

    /// <summary>
    /// Appends a character to the source, followed by a line break.
    /// </summary>
    public SourceBuilder AppendLine(char value)
    {
        if (_shouldIndent)
        {
            _builder.Append(new string(' ', _indentation * 4));
        }

        _builder.Append(value).AppendLine();
        _shouldIndent = true;
        return this;
    }

    /// <summary>
    /// Appends a string to the source, followed by a line break.
    /// </summary>
    public SourceBuilder AppendLine(string value)
    {
        if (_shouldIndent)
        {
            _builder.Append(new string(' ', _indentation * 4));
        }

        _builder.AppendLine(value);
        _shouldIndent = true;
        return this;
    }

    /// <summary>
    /// Appends a line of code to the source for each object in a collection.
    /// </summary>
    /// <param name="objects">The objects to generate code for.</param>
    /// <param name="getValue">Function that gets the source string for each object.</param>
    /// <typeparam name="TObject">The type of the objects in the collection.</typeparam>
    public SourceBuilder AppendLines<TObject>(IEnumerable<TObject> objects, Func<TObject, string> getValue)
    {
        foreach (var obj in objects)
        {
            AppendLine(getValue(obj));
        }

        return this;
    }

    /// <summary>
    /// Appends a line of code to the source for each object in an array.
    /// This overload will also add the separator character at the end of each line except the last.
    /// </summary>
    /// <param name="objects">The objects to generate code for.</param>
    /// <param name="getValue">Function that gets the source string for each object.</param>
    /// <param name="separator">The character to append to the end of each line.</param>
    /// <typeparam name="TObject">The type of the objects in the collection.</typeparam>
    public SourceBuilder AppendLines<TObject>(TObject[] objects, Func<TObject, string> getValue, char separator)
    {
        for (var i = 0; i < objects.Length; i++)
        {
            var obj = objects[i];
            Append(getValue(obj));

            if (i < objects.Length - 1)
            {
                Append(separator);
            }

            AppendLine();
        }

        return this;
    }

    /// <summary>
    /// Builds the final source code string.
    /// </summary>
    /// <returns>The built source code string.</returns>
    public override string ToString() => _builder.ToString();
}