name: Deploy Alpha Release to NuGet

on:
  push:
    workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Verify Git Tags
        run: git tag --list --sort=-version:refname

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Create Packages Directory
        run: mkdir packages
          
      - name: Build Local Packages for Integration Tests
        run: |
          dotnet pack src/Anima.EntityFrameworkCore.SourceGeneration/Anima.EntityFrameworkCore.SourceGeneration.csproj -o ./packages

      - name: Build the Projects
        run: dotnet build --configuration Release

      - name: Run Tests
        run: dotnet test --no-restore --verbosity normal
        
      - name: Install Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install Node Packages
        run: npm ci --no-fund
        
      - name: Release the Package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUGET_TOKEN: ${{ secrets.NUGET_API_KEY }}
        run: npx semantic-release